### ISSUE TITLE
The indicator doesn't reflect the current hide/show state

### ISSUE THREAD

**Issue by proninyaroslav** [amivaleo/Show-Desktop-Button#31]
When we hide or show windows, the indicator stays the same. This makes it difficult to understand what state it's in, because this state is not reset if we maximize or minimize the window manually.
I see three solutions to solve this problem:
1. Change indicator when changing state
2. Remove the ability to show windows, only hide (or leave as an option)
3. Reset the state if any window was maximized/minimized manually

**Comment by amivaleo** [comment]
How does Windows deal with that? Has Mac some equivalent button anywhere and what does it do if so?

**Comment by proninyaroslav** [comment]
Windows resets state if one visible window appears after hiding all windows.

**Comment by amivaleo** [comment]
My apologies for being lethargic.
I've checked this button on Windows and it's only sensible to mouse hovering.
I've been thinking about how to possibly implement any change in this direction into the extension and I believe it might require a lot of effort in order to make the button sensible to all possible states.
In fact, I see more than two possible states. At least:

all windows get hidden -> state 1
all hidden windows are shown -> state 2
all windows get hidden and the user open a new one -> state 3
more than one windows are open and the user hides one -> state 4

If and only if some other OS have mastered and solved this issue with an optimum solution, I will consider implementing ("copying") that. 🤔

**Comment by proninyaroslav** [comment]
Well, if it's quite difficult, then there are at least 2 more options that I suggested, (1) and (2). They assume the old behavior where the button's state doesn't depend on the window's state.

**Comment by amivaleo** [comment]
>They assume the old behavior

Yes, which I discarded because:
What if the user hides all windows by clicking on the extension's butotn and then he "de-hides" all of them by clicking on each window, one by one? In that case, the extension's button would show the state's (2) icon anyway. So I should add a loop that keeps checking all windows' states. I see no point in doing this. The fact that Windows does the same, makes me think its devs ended up with the very same.

Considering all possible scenarios, what's the rationale that makes you think it is good to implement any modification in the icon to reflect them (or only some of them)?

**Comment by proninyaroslav** [comment]
You misunderstood me. Currently the extension doesn't track the  windows state, its state is "looped in itself". But I can't see this state. Let's say I hide the windows and walked away to make myself a coffee. Next, I forgot that I minimized the windows, and maximized one or more windows manually, because the indicator doesn't display its state and I thought that the windows were not minimized using the button.

**Comment by amivaleo** [comment]
And... What's the issue with that?

If, at the point, you click the indicator, any left minimized windows get de-minimized. What should it do, according to your opinion?

In the very same conditions, if you click on Windows' button, it minimizes any window that you have de-minimized after your coffee. So yes, there's a difference in the behaviour. BUT, after the last action, Windows ignores those window that haven't been touched after your coffee.

I hope to make it clearer this way:

You have only 4 windows, A, B, C, D, and all of them are open.

In gnome:
1 click on the indicator -> A B C D get minimized
2 go for a coffee
3 de-minimize only A and B. C and D are stil minimized
4 click on the indicator -> **C and D get de-minimized**, so A B C D are all displayed/de-minimized.

You're now back to point 1.


In Windows:
1 click on the indicator -> A B C D get minimized
2 go for a coffee
3 de-minimize only A and B. C and D are stil minimized
4 click on the indicator -> **A and B get minimized**. C and D are ignored.
5 clink on the indicator again -> A and B get de-minimized. C and D are ignored.

Points 4 and 5 go on forever unless you manually de-minimize C or D.

I bolded the difference between my extension and Windows.

I believe Windows' approach is worse, since it leads to ignore currently open windows. I want the user to never forget them. In Windows the dash bar is always there, and so its devs might have tought that their approach is still fine. In gnome the dash is hidden and so there isn't a "passive" way (I mean: without having to go to the overview) to have a constant look at what's open.

I believe the indicator in Gnome should work as it does currently.

What changes would you suggest in the number list above and why?

**Comment by proninyaroslav** [comment]
At this point, I'm not suggesting changing **behavior**. I suggest only to **indicate the button state** with different icons. So that I can understand if it's in the "All hidden" or "All shown" state, instead of playing the game "What state is the button in now" by pressing it once or twice to understand.

**Comment by amivaleo** [comment]
Ok, now I got it.

I'd like to focus on avoiding those scenarios in which the indicator needs to be clicked twice (or forever!) before it actually does something.

Basically I want the button to
(1) hide any open window under any circumstances,
(2) show all minimized windows (if any) if all of them minimized.

This was the intended behaviour since ever, indeed. That's also why I discarded the icon switching feature.

I'd like to stick to this. Unfortunately, I need some spare time before I can tackle this issue, and so it will take some time...
