### ISSUE TITLE
 A new way to return to the desktop 

### ISSUE THREAD

**Issue by q962** [amivaleo/Show-Desktop-Button#32]
![图片](https://user-images.githubusercontent.com/15686075/202900770-94410614-b8ac-41aa-b662-af60d2e2295f.png)

I don't know what this mode is called.
I want to mouse right click the non application area to return to the desktop

**Comment by amivaleo** [comment]
This is not related to this extension and beyond its scope.
A dedicated and different extension would meet your needs.
This extension https://extensions.gnome.org/extension/3826/click-to-close-overview/ on EGO might suit your request.

**Comment by q962** [comment]
No, this is not the same.
click to close overview just closes the applist window and does not return to the desktop. I do not need to return to the desktop in that window.

**Comment by amivaleo** [comment]
You want to minimize all windows and close the overview by right-clicking on an empty area in the overview?
This is beyond the scope of this extension anyway.

**Comment by q962** [comment]
When using multiple screens, the button triggering method is not enough.

Well, it seems that I can only take time to study and write and expand it myself.

**Comment by amivaleo** [comment]
> When using multiple screens, the button triggering method is not enough.

I believe it's questionable.
Anyway, this extension won't deal with what happens in the overview. The only way of triggering any action from this extension will remain by clicking on the panel indicator.

**Comment by q962** [comment]
For me, when I no longer need multiple screens, I can bring other screens back to the desktop and enjoy my wallpaper.

The way you use the button causes all screens to return to the desktop. That's not my purpose. But there is only one button, and it is impossible to distinguish between multiple screens.

**Comment by amivaleo** [comment]
I'm struggling to understand here.

"return to the desktop", to me, means "closing the overview". But I do not understand what you mean by "bring other screens back to the desktop". I guess "screens" stand for "workspaces" in what you wrote.

This extension do not deal with workspaces/screens, and treat them as completely different spaces. It only deals with open application windows.

The indicator/button minimizes all open windows in the current workspace only, without affecting the others. If multiple monitors are attached, the extension (un)minimizes all visible windows in the current workspace and also in all the other attached monitors.

If the user switches to another workspace, the indicator/button treats it as a completeley sandboxed space.

This is the desired behaviour. I also believe this is the expected behaviour considering.

Please provide a complete and clear explanation of the scenario in which you state that the extension should work differently.

**Comment by q962** [comment]
"return to desktop" for me means minimizing all available apps and displaying the wallpaper completely.
Just like Show-Desktop-Button does. Minimize all visual applications.

Different workspaces do need to be separate spaces.

I'm just using a workspace at the moment

What controls does a single tap super key display? Just like my picture.

What controls does a quick tap of the super key show?

Allow me to use controls to represent different things

Clicking the charm key once, and then clicking the left mouse button in the non-application area, will close the current control (Overview?). As a result, nothing happened. Quite, nothing has changed.

I need to minimize the application in the current screen by right-clicking on a non-application area.

**Comment by amivaleo** [comment]
> Different workspaces do need to be separate spaces.

I strongly believe there's a strong rationale for which they do need to be treated separately by this extension.

> Clicking the charm key once, and then clicking the left mouse button in the non-application area, will close the current control (Overview?). As a result, nothing happened. Quite, nothing has changed.

That's how gnome-shell works according to its devs, not according to me.
If don't install this extension and try to minimize all windows one by one, you will get the very same exact behaviour.

Doing anything about that is beyond the scope of this extension, whose only purpose is to provide a toggle button to minimize/uniminimize open windows.

> I need to minimize the application in the current screen by right-clicking on a non-application area.

You're asking for a completely different extension, which minimizes open windows by right-clicking on an empty area of the overview.
This is not related to this extension.

My apologies, but I'm not planning to work on coding such extension.

**Comment by q962** [comment]
Or use super+d to minimize the app on the current screen, the button position is honestly a bit far. And it can't distinguish between multiple screens, which is somewhat inconvenient.

It seems that I had to learn GNOMO extensions on my own.

Thank you for your reply

**Comment by q962** [comment]
I know what workspaces are all about.
Monitors is hardware for me, usually it only has one displayable area, which is the screen

So screens represents one of the monitors, not all monitors

What are the five ways? I didn't find instructions

**Comment by amivaleo** [comment]
I already answered on the workspace/screens/monitors point.

> What are the five ways? I didn't find instructions

Many extensions come with some settings. Extensions's authors are not requested to provide instructions on where to find, since we would all provide the same instructions..

This extension has settings. Check your "installed extension" on EGO. The link is: https://extensions.gnome.org/local/ page

**Comment by q962** [comment]
。。。 , I knew there was a settings button in that location, but I didn't notice it 🤐
