### ISSUE TITLE
Multiple Monitors

### ISSUE THREAD

**Issue by nater1983** [amivaleo/Show-Desktop-Button#35]
Do you think this extension could support multiple monitors in the future?

**Comment by amivaleo** [comment]
Hi!
My apologies for the late reply, I'm on holiday and don't check emails much often nor I spend much time on my pc lately.

Last time I checked, this extension worked fine in the following configuration:
- external monitor plugged in + laptop's screen on: separate display.
By "worked fine" I mean that the two monitors worked like if they were one single screen, so that when I hide windows, they get hidden in both screen and viceversa.

I can't check other configurations that require other monitors and, currently, I don't have access to an external monitor, which is in my work place.

What do you experience?
What's your setup?
How the extension work with your setup?
How do you think it should work?

Please, be as descriptive as you can.

**Comment by nater1983** [comment]
I h ave 2 monitor's and show desktop only shows up on one screen and not the other. 

I have Gnome 43.2 with Slackware-Current. Show Desktop shows up on the primary monitor and I was just wondering if it would be possible to show up on both the primary and secondary monitor.

**Comment by nater1983** [comment]
Or could we have the option if there is more then one monitor to include it with them as well?

**Comment by amivaleo** [comment]
Apologies again for the late reply.
I'm back at work and... To all the ordinary things that fill my spare time.

Gnome doesn't add a panel to the non-primary monitors. So there's no place for me to put an indicator.

There might be extentions that add a panel in each monitor. As far as I know, no other extension puts anything in those panels. I believe that such feature would require a joint effort among extentions' devs.
I consider this request to be beyond the scope of this (and probably any other) extension.

Thanks for your interest. :)
