### ISSUE TITLE
Adding feature: setting indicator position on the panel

### ISSUE THREAD

**Issue by amivaleo** [amivaleo/Show-Desktop-Button#9]
I need help understanding and (only then) implementing the feature in the subject.

How to code the setting window?
How to link changes in that window with the extension.js file and the other files?

**Comment by AceOfSpadez54** [comment]
Cannot help with that, however I can help with moving the button location.
In extension.js on line 58 for me in Sublime
_Main.panel._rightBox.insert_child_at_index(panelIndicator, 0);_
You simply change right to center or left as follows:
_Main.panel._leftBox.insert_child_at_index(panelIndicator, 0);_
and that somewhat fixes it. 
I say somewhat because I personally like it in the exact center of the panel, and this moves it to the beginning of the center box, or the very far left if you choose that option.

**Comment by amivaleo** [comment]
Thank you dude, but there's already some code in version7 (currently  in the review queue on EGO) that restores such feature. It's pretty rough, I'd say junk, but that's the quickest solution I could find.

**Comment by amivaleo** [comment]
Half-baked in version 8.

**Comment by amivaleo** [comment]
Duplicate #12.
I prefer to keep this closed.
